[package]
name = "swc-plugin"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
swc_core = { version = "0.59.*", features = ["ecma_plugin_transform"] }
